import {StyleSheet} from 'react-native';
import {SIZES, FONTS, COLORS} from '@constants/theme';

export const styles = StyleSheet.create({
  cartHeading: {...FONTS.body3_bold},
  cartTriggerView: {
    flexDirection: 'row',
    width: SIZES.hundred,
    height: 80,
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
  },
  triggerLeft: {
    width: SIZES.fifty,
    flexDirection: 'row',
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
  },
  totalTxt: {
    ...FONTS.body3,
    color: COLORS.black,
    marginRight: SIZES.base,
  },
  priceTxt: {
    ...FONTS.body3_bold,
    color: COLORS.black,
    marginRight: SIZES.radius,
  },
  chevron: {width: 12, resizeMode: 'contain'},
  triggerRight: {
    width: SIZES.fifty,
    height: 70,
  },
  continueBtn: {height: 40, width: SIZES.eighty, alignSelf: 'flex-end'},
  methodContainer: {
    width: SIZES.hundred,
    borderWidth: 1,
    borderColor: COLORS.secondaryUltra,
    padding: SIZES.radius,
    borderRadius: SIZES.base,
    flexDirection: 'row',
    height: 80,
    alignItems: 'center',
  },
  addressContainer: {
    width: SIZES.hundred,
    // borderWidth: 1,
    // borderColor: COLORS.secondaryUltra,
    paddingHorizontal: SIZES.radius,
    borderRadius: SIZES.base,
    backgroundColor: COLORS.white,
  },
  leftView: {width: SIZES.fifteen},
  midView: {width: SIZES.seventyFive},
  rightView: {width: SIZES.ten, alignItems: 'flex-end'},
  tickImage: {width: 15, height: 15, resizeMode: 'contain'},
  methodImg: {width: 30, height: 30, resizeMode: 'contain'},
  methodTitle: {color: COLORS.black, ...FONTS.body5},
  methodExpiry: {color: COLORS.secondaryUltra, ...FONTS.body5},
  methodDefaultTxt: {color: COLORS.black, ...FONTS.body5_bold},
  bSheetTop: {height: SIZES.ten},
  bSheetTopHeading: {...FONTS.h3},
  addPaymentMethodButton: {
    width: SIZES.fourtyFive,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderWidth: 1,
    padding: SIZES.base,
    borderRadius: SIZES.radius,
  },
  radioBtn: {width: 20, height: 20, resizeMode: 'contain'},
  addPaymentMethodButtonTxt: {...FONTS.body5},
  bSheetMid: {height: SIZES.sixty, justifyContent: 'center'},
  cvvView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfInput: {width: '48%'},
  checkbox: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginRight: SIZES.radius,
  },
  bSheetBottom: {
    height: SIZES.twenty,
    justifyContent: 'flex-end',
  },

  // payment info end

  addressNameTitle: {
    ...FONTS.body5,
    color: COLORS.txtGray,
    marginBottom: SIZES.minor,
  },
  addressName: {
    ...FONTS.body5,
    color: COLORS.black,
    flexWrap: 'wrap',
    marginBottom: SIZES.minor,
  },
  makeDefaultView: {width: SIZES.fifty},

  calcView: {
    width: SIZES.thirtyFive,
    backgroundColor: COLORS.white,
    height: 50,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    borderRadius: SIZES.radius,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  calcImg: {width: 15, height: 15, resizeMode: 'contain'},
  calcTxt: {...FONTS.body3},

  balloonSectionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  pillsContainer: {
    width: SIZES.hundred,
    height: 50,
    backgroundColor: COLORS.bgGray,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    borderRadius: SIZES.base,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SIZES.minor,
  },
  pillBtn: {
    width: SIZES.thirty,
    height: SIZES.hundred,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZES.base,
  },
  logo: {width: 100, height: 70, resizeMode: 'contain', alignSelf: 'center'},
  shadowContainer: {
    backgroundColor: '#fff',
    elevation: 5, // elevation for shadow on Android
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderWidth: 1, // Border width to create a border on the top
    borderColor: '#ddd', // Border color to match with the shadow color
    borderRadius: 10,
    width: SIZES.hundred,
  },
  editImg: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    marginRight: SIZES.radius,
  },
  editTxt: {color: COLORS.secondary, ...FONTS.body5_bold},
  balloons: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    marginRight: SIZES.radius,
  },
  qty: {...FONTS.body5, color: COLORS.black},
  character: {
    height: 100,
    width: 100,
    borderRadius: 100,
    overflow: 'hidden',
    marginRight: SIZES.radius,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SIZES.radius,
  },
  characterImg: {height: 60, width: 60, resizeMode: 'contain'},
  labelTxt: {...FONTS.body5, color: COLORS.txtGray},
  labelVlue: {...FONTS.body5, color: COLORS.black},
  thankyouContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: SIZES.ninty,
    alignSelf: 'center',
  },
  thankyouImgImg: {width: SIZES.seventy, height: 200, resizeMode: 'contain'},
  thankyouHeading: {...FONTS.body2_bold, color: COLORS.black},
  thankyouContent: {
    ...FONTS.body5,
    textAlign: 'center',
    marginTop: SIZES.radius,
    color: COLORS.txtGray,
  },
});
