import { StyleSheet } from 'react-native';
import { SIZES, COLORS, FONTS } from '@constants/theme';

export const styles = StyleSheet.create({
  backImg: { width: 20, height: 20, resizeMode: 'cover', aspectRatio: 1 },
  mainImgView: {
    width: SIZES.eighty,
    height: 300,
    alignItems: 'center',
    alignSelf: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderRadius: SIZES.base,
    borderColor: COLORS.grayLight,
  },
  mainImg: {
    width: SIZES.hundred,
    height: SIZES.hundred,
    resizeMode: 'cover',
    aspectRatio: 1,
    backgroundColor: COLORS.white,
  },
  otherImgView: {
    width: SIZES.eighty,
    height: 100,
    alignItems: 'center',
    alignSelf: 'center',
    overflow: 'hidden',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  otherImg: {
    // flex: 1,
    width: 100,
    height: 90,
    resizeMode: 'contain',
    aspectRatio: 1,
    borderWidth: 1,
    borderRadius: SIZES.base,
    borderColor: COLORS.grayLight,
    backgroundColor: COLORS.white,
    paddingRight: SIZES.padding,
    paddingHorizontal: SIZES.padding,
    paddingVertical: SIZES.minor,
    marginRight: SIZES.radius,
  },
  content: { paddingHorizontal: SIZES.padding },
  headingView: { width: SIZES.sixtyFive },
  heading: { ...FONTS.body2_bold, color: COLORS.black },
  price: { ...FONTS.body2_bold, color: COLORS.primary },
  calcView: {
    width: SIZES.thirtyFive,
    backgroundColor: COLORS.white,
    height: 50,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    borderRadius: SIZES.radius,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  calcImg: { width: 15, height: 15, resizeMode: 'contain' },
  calcTxt: { ...FONTS.body3 },
  descHeading: { ...FONTS.body4_medium, color: COLORS.black },
  descTxt: { ...FONTS.body4, color: COLORS.txtGray },
});
