export default {
  api: {
    baseURL: 'https://phplaravel-1473314-5573074.cloudwaysapps.com/api/v1',
  },
  apiName: {
    socialLogin: 'auth/social-login',
    login: 'auth/login',
    register: 'auth/register',
    getProfile: 'auth/me',
    updateProfile: 'auth/update-profile',
    logoutUser: 'auth/logout',
    getOrders: 'get-orders',
    utilsAPI: 'get-utils',
    homeAPI: 'home',
    details: 'product-detail',
    productList: 'product-listing',
    search: 'product-search',
    searchTerm: 'product-term-search',
    getCart: 'get-cart',
    getTimeSlots: 'timeslots',
    addToCart: 'add-to-cart',
    deleteItemFromCart: 'delete-cart',
    completeCart: 'complete-cart',
    onlinePayment: 'dibsy/initiate',
    bindGuestUser: 'bind-guest',
    bindAutheticatedUser: 'bind-user',
    attachImage: 'attach-image',
    attachWrapper: 'attach-wrapper',
    attachGiftCard: 'attach-gift-card',
    applyCoupon: 'apply-coupon',
    removeCoupon: 'remove-coupon',
    getAddresses: 'get-addresses',
    addAddress: 'add-address',
    addAddressToCart: 'add-order-address',
  },
  webviewUrl: {},
};
