const SOFT_RELOAD_TRUE = 'SOFT_RELOAD_TRUE';
const SOFT_RELOAD_FALSE = 'SOFT_RELOAD_FALSE';
const HARD_RELOAD_TRUE = 'HARD_RELOAD_TRUE';
const HARD_RELOAD_FALSE = 'HARD_RELOAD_FALSE';

export default {
  SOFT_RELOAD_TRUE,
  SOFT_RELOAD_FALSE,
  HARD_RELOAD_TRUE,
  HARD_RELOAD_FALSE,
};
