import { StyleSheet } from 'react-native';
import { COLORS, FONTS, SIZES } from '@constants/theme';

export const styles = StyleSheet.create({
  topRow: {
    backgroundColor: COLORS.secondaryLite,
    height: 100,
    padding: SIZES.padding,
    flexDirection: 'row',
    alignItems: 'center',
  },
  topRowLeftView: { width: SIZES.thirty },
  topImg: {
    borderWidth: 2,
    borderColor: COLORS.secondaryUltra,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  topRowRightView: { width: SIZES.seventy },
  topRowName: { ...FONTS.body3_bold, color: COLORS.black },
  topRowEmail: { ...FONTS.body4_medium, color: COLORS.black },
  contentContainer: { paddingHorizontal: SIZES.padding },
  listItem: {
    borderRadius: SIZES.radius,
    backgroundColor: COLORS.white,
    padding: SIZES.radius,
  },
  listItemLeftView: {
    width: SIZES.seventy,
    flexDirection: 'row',
    alignItems: 'center',
  },
  toolImg: { width: 35, height: 35, resizeMode: 'contain' },
  toolTxt: {
    ...FONTS.body5_bold,
    color: COLORS.black,
    marginLeft: SIZES.base,
  },
  listItemRightView: {
    width: SIZES.thirty,
    alignItems: 'flex-end',
  },
  forwardImg: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    transform: [{ rotate: '180deg' }],
    tintColor: COLORS.secondaryUltra,
  },
  balloons: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    marginRight: SIZES.radius,
  },
  character: {
    height: 100,
    width: 100,
    borderRadius: 100,
    overflow: 'hidden',
    marginRight: SIZES.radius,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SIZES.radius,
  },
  characterImg: { height: 60, width: 60, resizeMode: 'contain' },

  // Account page ends
  logo: { width: 100, height: 70, resizeMode: 'contain', alignSelf: 'center' },
  pillsContainerLogin: {
    width: SIZES.sixty,
    height: 50,
    backgroundColor: COLORS.bgGray,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    borderRadius: SIZES.base,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SIZES.minor,
    alignSelf: 'center'
  },
  pillBtnLogin: {
    width: SIZES.fourtyFive,
    height: SIZES.hundred,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZES.base,
  },
  pillsContainer: {
    width: SIZES.hundred,
    height: 50,
    backgroundColor: COLORS.bgGray,
    borderWidth: 1,
    borderColor: COLORS.grayLight,
    borderRadius: SIZES.base,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SIZES.minor,
  },
  pillBtn: {
    width: SIZES.thirty,
    height: SIZES.hundred,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZES.base,
  },

  // Order end

  smallHeading: { ...FONTS.body4_bold, color: COLORS.black },
  smallInfoTxt: { ...FONTS.body5_medium, color: COLORS.black },
  orderItemItemTitle: { ...FONTS.body5, color: COLORS.black },
  orderItemItemPrice: { ...FONTS.body4_bold, color: COLORS.black },
  orderItemItemQty: { ...FONTS.body5, color: COLORS.black },
  moreInfo: {
    backgroundColor: COLORS.bgGray,
    padding: SIZES.base,
    marginHorizontal: SIZES.radius,
  },
  smallGap: { paddingVertical: SIZES.minor },
  totalTxt: { ...FONTS.body4_bold, color: COLORS.black },
  smallTotalTxt: { ...FONTS.body4_bold, color: COLORS.black },
  // OrderDetailend

  methodContainer: {
    width: SIZES.hundred,
    borderWidth: 1,
    borderColor: COLORS.secondaryUltra,
    padding: SIZES.radius,
    borderRadius: SIZES.base,
    flexDirection: 'row',
    height: 80,
    alignItems: 'center',
  },
  addressContainer: {
    width: SIZES.hundred,
    borderWidth: 1,
    borderColor: COLORS.secondaryUltra,
    padding: SIZES.radius,
    borderRadius: SIZES.base,
    backgroundColor: COLORS.white,
  },
  leftView: { width: SIZES.fifteen },
  midView: { width: SIZES.seventyFive },
  rightView: { width: SIZES.ten, alignItems: 'flex-end' },
  tickImage: { width: 15, height: 15, resizeMode: 'contain' },
  methodImg: { width: 30, height: 30, resizeMode: 'contain' },
  methodTitle: { color: COLORS.black, ...FONTS.body5 },
  methodExpiry: { color: COLORS.secondaryUltra, ...FONTS.body5 },
  methodDefaultTxt: { color: COLORS.black, ...FONTS.body5_bold },
  bSheetTop: { height: SIZES.ten },
  bSheetTopHeading: { ...FONTS.h3 },
  addPaymentMethodButton: {
    width: SIZES.fourtyFive,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderWidth: 1,
    padding: SIZES.base,
    borderRadius: SIZES.radius,
  },
  radioBtn: { width: 20, height: 20, resizeMode: 'contain' },
  addPaymentMethodButtonTxt: { ...FONTS.body5 },
  bSheetMid: { height: SIZES.sixty, justifyContent: 'center' },
  cvvView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  halfInput: { width: '48%' },
  checkbox: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginRight: SIZES.radius,
  },
  bSheetBottom: {
    height: SIZES.twenty,
    justifyContent: 'flex-end',
  },

  // payment info end

  addressNameTitle: {
    ...FONTS.body5,
    color: COLORS.txtGray,
    marginBottom: SIZES.minor,
  },
  addressName: {
    ...FONTS.body5,
    color: COLORS.black,
    flexWrap: 'wrap',
    marginBottom: SIZES.minor,
  },
  makeDefaultView: { width: SIZES.fifty },
});
